// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnejXG_ZwO_BBl_R4ZoYvgz2rQHw_Blbs',
    appId: '1:734708733074:web:fe941d166997785375424b',
    messagingSenderId: '734708733074',
    projectId: 'smartbank-ec',
    authDomain: 'smartbank-ec.firebaseapp.com',
    storageBucket: 'smartbank-ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIRx-NxNNqaMK3vsB034GYmarXtIwd9tE',
    appId: '1:734708733074:android:90883b4be0b8136375424b',
    messagingSenderId: '734708733074',
    projectId: 'smartbank-ec',
    storageBucket: 'smartbank-ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdN474VWQllDK61Y_Z26Y67iED0W10oNU',
    appId: '1:734708733074:ios:c864e6b8488a530875424b',
    messagingSenderId: '734708733074',
    projectId: 'smartbank-ec',
    storageBucket: 'smartbank-ec.firebasestorage.app',
    iosBundleId: 'com.example.smartbankEc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdN474VWQllDK61Y_Z26Y67iED0W10oNU',
    appId: '1:734708733074:ios:c864e6b8488a530875424b',
    messagingSenderId: '734708733074',
    projectId: 'smartbank-ec',
    storageBucket: 'smartbank-ec.firebasestorage.app',
    iosBundleId: 'com.example.smartbankEc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnejXG_ZwO_BBl_R4ZoYvgz2rQHw_Blbs',
    appId: '1:734708733074:web:45776c5fc36ff1b275424b',
    messagingSenderId: '734708733074',
    projectId: 'smartbank-ec',
    authDomain: 'smartbank-ec.firebaseapp.com',
    storageBucket: 'smartbank-ec.firebasestorage.app',
  );
}
